version: '2'
services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  web:
    image: node:10.3.0
    container_name: ${PROJECT_NAME}-node
    working_dir: /usr/src/app
    expose:
      - "3000"
    entrypoint:
      - "yarn"
      - "deploy"
    volumes:
      - "./:/usr/src/app"
