version: '2'
services:
  nginx:
    container_name: ${PROJECT_NAME}-stage-nginx
    environment:
      VIRTUAL_HOST: ${STAGE_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${STAGE_VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: always
    networks:
      - nginx-proxy
      - default

  web:
    container_name: ${PROJECT_NAME}-stage-node
    environment:
      QINIU_URL: ${STAGE_QINIU_URL}
    restart: always
    networks:
      - default

networks:
  nginx-proxy:
    external:
      name: nginxproxyservice_default
